# Generated by Django 4.1 on 2022-09-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_alter_clientes_nombre_alter_clientes_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='direcciion',
            new_name='direccion',
        ),
    ]
